eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
spring:
  datasource:
    name: dev 
    url: jdbc:mysql://127.0.0.1:3306/snailmall
    username: root
    password: root
  rabbitmq:
    host: 106.52.213.64
    port: 5672
    username: guest
    password: guest
zk:
  host: 106.52.213.64
redis:
    host: 106.52.213.64
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000

    